name: EconCommands
version: ${project.version}${describe}
description: Economy commands utilizing a Vault backend
author: meiskam

main: org.shininet.bukkit.econcommands.EconCommands
database: false

depend: [Vault]
softdepend: [WorldEdit]

permissions:
  econcommands.balance:
    description: Can get balance of self or another player
    children:
      econcommands.balance.self:
        description: Can get balance of self
      econcommands.balance.other:
        description: Can get balance of another player
  econcommands.pay:
    description: Can transfer currency to another player
  econcommands.admin:
    description: Can fiddle with other players accounts
    default: op
    children:
      econcommands.admin.add:
        description: Can add currency to a players account
      econcommands.admin.remove:
        description: Can remove currency from a players account
      econcommands.admin.set:
        description: Can set the currency amount of a players account