name: EconCommands
version: ${project.version}${describe}
description: Economy commands utilizing a Vault backend
author: meiskam

main: org.shininet.bukkit.econcommands.EconCommands
database: false

depend: [Vault]